import './globals.css'
import Script from 'next/script'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-pattern'>
        <div className='min-h-[73vh]'>
          {children}
        </div>
      </body>
    </html>
  )
}
